### ISSUE TITLE
SPIFFS Not Supported on avr

### ISSUE THREAD

**Issue by iconnor** [Jaycar-Electronics/WiFi-Rover#1]
Getting this error when trying to upload the server part (5,6,7 are on).

![image](https://user-images.githubusercontent.com/22875/66365244-ab1fc980-e9cf-11e9-909b-03d927003cd8.png)

**Comment by iconnor** [comment]
Found that I needed additional boards:

Open Arduino IDE and go to files and click on the preference in the Arduino IDE.

Add the following link to the Additional Manager URLS section: "http://arduino.esp8266.com/stable/package_esp8266com_index.json" and press the OK button.

Then click Tools> Board Manager. Type "ESP8266" in the text box to search and install the ESP8266 software for Arduino IDE.

**Comment by Jaycar-Electronics** [comment]
Yep; We'll try and make this more clear-er in the readme: 686ed4c and 1c64893

Good for figuring it out though, hope you've enjoyed it
